StackCalculator
Minkerr/Programming2Semester pull request #1
Opened 2024-04-02 22:37 UTC by Minkerr

2024-04-03 17:30 UTC, yurii-litvinov requested changes

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackCalculatorTest.cs
> +    }
```suggestion
    private bool ApproximatelyEqual(double first, double second)
        => first >= second - DELTA && first <= second + DELTA;
```
Используйте expression-bodied methods везде, где это можно (то есть метод из одного оператора)

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackCalculatorTest.cs
> +        StackCalculator calculator = new StackCalculator(stack);
```suggestion
        StackCalculator calculator = new(stack);
```
Не пишите в объявлении тип дважды

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackCalculatorTest.cs
> +        // actual
act :)

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackCalculatorTest.cs
> +        Assert.That(ApproximatelyEqual(actual, 0.3), Is.True);
Есть Is.EqualTo(...).Within, ApproximatelyEqual не нужна (задача-то частая, значит, уже решена)

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackCalculatorTest.cs
> +        StackCalculator calculator = new StackCalculator(stack);
Это можно было в SetUp вынести, а calculator сделать полем.

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackTest.cs
> +using Calculator.exceptions;
Пространства имён в .NET всегда именуются с заглавной

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator.Tests/StackTest.cs
> +
Лишняя пустая строчка

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/Programm.cs
> +}
Это вообще не нужно, можно указать в проектном файле в OutputType, что собирается Library, тогда Main можно будет не писать вовсе. Кстати, "Program" по-английски пишется с одной "m".

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/Stack.cs
> +public interface Stack
Надо комментарий и к самому интерфейсу тоже

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/Stack.cs
> +    // put new element on top of the stack
Надо комментарии в формате XML Documentation, с ///

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/StackArrayImplementation.cs
> +public class StackArrayImplementation : Stack // list stack implementation
Комментарии пишутся над комментируемой сущностью, не сбоку

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/StackArrayImplementation.cs
> +    private const int DEFAULT_CAPASITY = 1024;
Оно "CAPACITY", и константы именуются в PascalCase (вообще, стоит пролистать https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names)

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/StackArrayImplementation.cs
> +    }
Можно было тут использовать constructor chaining

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/StackArrayImplementation.cs
> +            throw new StackIsFullException();
Не, это как-то непрофессионально. Используйте Array.Resize

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/StackArrayImplementation.cs
> +    }
На всякий случай напоминаю про expression-bodied-методы

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/StackListImplementation.cs
> +        if(stackList.Count == 0) // one cannot delete an item from an empty stack
Пробела не хватает, тут и ниже

2024-04-03 17:30 UTC, yurii-litvinov commented on StackCalculator/StackCalculator/exceptions/StackCalculatorIncorrectInputException.cs
> +public class StackCalculatorIncorrectInputException : SystemException
К исключениям тоже нужны комментарии

2024-04-06 08:45 UTC, Minkerr commented on StackCalculator/StackCalculator.Tests/StackCalculatorTest.cs
> +        StackCalculator calculator = new StackCalculator(stack);
> Это можно было в SetUp вынести, а calculator сделать полем.

Не совсем понял, что именно имеется ввиду. Сделал, что TestCaseData это калькулятор, а не стэк, то есть теперь калькулятор в каждом тесте не создаётся по новой

2024-05-03 08:47 UTC, merged